# Deno Dockerfile on server/Dockerfile

services:
  deno:
    build: ./server
  front:
    build:
      context: front
    ports:
      - "80:80"
    depends_on:
      - deno
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
