# Deno Dockerfile on server/Dockerfile

services:
  deno:
    build: ./server
    ports:
      - "8001:8001"
      - "8000:8000"
    networks:
      - nginx-proxy
  front:
    build:
      context: front
    ports:
      - "80:80"
    depends_on:
      - deno
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nginx-proxy
networks:
  nginx-proxy:
    external: true
